// <auto-generated />
using System;
using FamilyCare.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FamilyCare.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(FamilyCareDbContext))]
    partial class FamilyCareDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FamilyCare.Domain.FamilyManagement.Family", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<Guid>("OwnerUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_user_id");

                    b.HasKey("Id")
                        .HasName("pk_families");

                    b.HasIndex("OwnerUserId")
                        .HasDatabaseName("ix_families_owner_user_id");

                    b.ToTable("families", (string)null);
                });

            modelBuilder.Entity("FamilyCare.Domain.FamilyManagement.FamilyMember", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateOnly>("BirthDate")
                        .HasColumnType("date")
                        .HasColumnName("birth_date");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("display_name");

                    b.Property<Guid>("FamilyId")
                        .HasColumnType("uuid")
                        .HasColumnName("family_id");

                    b.Property<DateTime>("JoinedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("joined_at");

                    b.Property<int>("Relationship")
                        .HasColumnType("integer")
                        .HasColumnName("relationship");

                    b.Property<int>("Role")
                        .HasColumnType("integer")
                        .HasColumnName("role");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_family_members");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_family_members_user_id");

                    b.HasIndex("FamilyId", "UserId")
                        .IsUnique()
                        .HasDatabaseName("ix_family_members_family_id_user_id");

                    b.ToTable("family_members", (string)null);
                });

            modelBuilder.Entity("FamilyCare.Domain.FamilyManagement.Invitation", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("email");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<Guid>("FamilyId")
                        .HasColumnType("uuid")
                        .HasColumnName("family_id");

                    b.Property<int>("ProposedRelationship")
                        .HasColumnType("integer")
                        .HasColumnName("proposed_relationship");

                    b.Property<int>("ProposedRole")
                        .HasColumnType("integer")
                        .HasColumnName("proposed_role");

                    b.Property<DateTime?>("RespondedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("responded_at");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("pk_invitations");

                    b.HasIndex("Email")
                        .HasDatabaseName("ix_invitations_email");

                    b.HasIndex("FamilyId", "Status")
                        .HasDatabaseName("ix_invitations_family_id_status");

                    b.ToTable("invitations", (string)null);
                });

            modelBuilder.Entity("FamilyCare.Domain.FamilyManagement.PrivacyRule", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid[]>("AllowedMemberIds")
                        .IsRequired()
                        .HasColumnType("uuid[]")
                        .HasColumnName("allowed_member_ids");

                    b.Property<int>("Category")
                        .HasColumnType("integer")
                        .HasColumnName("category");

                    b.Property<Guid>("FamilyMemberId")
                        .HasColumnType("uuid")
                        .HasColumnName("family_member_id");

                    b.Property<int>("Scope")
                        .HasColumnType("integer")
                        .HasColumnName("scope");

                    b.HasKey("Id")
                        .HasName("pk_privacy_rules");

                    b.HasIndex("FamilyMemberId", "Category")
                        .IsUnique()
                        .HasDatabaseName("ix_privacy_rules_family_member_id_category");

                    b.ToTable("privacy_rules", (string)null);
                });

            modelBuilder.Entity("FamilyCare.Domain.Identity.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<Guid?>("ReplacedByTokenId")
                        .HasColumnType("uuid")
                        .HasColumnName("replaced_by_token_id");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at");

                    b.Property<string>("RevokedReason")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("revoked_reason");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("token_hash");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_refresh_tokens");

                    b.HasIndex("TokenHash")
                        .IsUnique()
                        .HasDatabaseName("ix_refresh_tokens_token_hash");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_refresh_tokens_user_id");

                    b.ToTable("refresh_tokens", (string)null);
                });

            modelBuilder.Entity("FamilyCare.Domain.Identity.User", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("email");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("password_hash");

                    b.Property<int>("PreferredLanguage")
                        .HasColumnType("integer")
                        .HasColumnName("preferred_language");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_users_email");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("FamilyCare.Domain.MedicalHistory.Allergy", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("FamilyMemberId")
                        .HasColumnType("uuid")
                        .HasColumnName("family_member_id");

                    b.Property<DateOnly?>("FirstObservedAt")
                        .HasColumnType("date")
                        .HasColumnName("first_observed_at");

                    b.Property<string>("Reaction")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("reaction");

                    b.Property<int>("Severity")
                        .HasColumnType("integer")
                        .HasColumnName("severity");

                    b.Property<string>("Substance")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("substance");

                    b.HasKey("Id")
                        .HasName("pk_allergies");

                    b.HasIndex("FamilyMemberId")
                        .HasDatabaseName("ix_allergies_family_member_id");

                    b.ToTable("allergies", (string)null);
                });

            modelBuilder.Entity("FamilyCare.Domain.MedicalHistory.Appointment", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("DoctorName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("doctor_name");

                    b.Property<Guid>("FamilyMemberId")
                        .HasColumnType("uuid")
                        .HasColumnName("family_member_id");

                    b.Property<string>("Location")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("location");

                    b.Property<string>("Notes")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("notes");

                    b.Property<DateTime>("ScheduledAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("scheduled_at");

                    b.Property<string>("Specialty")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("specialty");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("pk_appointments");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_appointments_status");

                    b.HasIndex("FamilyMemberId", "ScheduledAt")
                        .HasDatabaseName("ix_appointments_family_member_id_scheduled_at");

                    b.ToTable("appointments", (string)null);
                });

            modelBuilder.Entity("FamilyCare.Domain.MedicalHistory.Attachment", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("file_name");

                    b.Property<string>("MimeType")
                        .IsRequired()
                        .HasMaxLength(127)
                        .HasColumnType("character varying(127)")
                        .HasColumnName("mime_type");

                    b.Property<Guid>("OwnerEntityId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_entity_id");

                    b.Property<int>("OwnerType")
                        .HasColumnType("integer")
                        .HasColumnName("owner_type");

                    b.Property<long>("SizeBytes")
                        .HasColumnType("bigint")
                        .HasColumnName("size_bytes");

                    b.Property<string>("StoragePath")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("storage_path");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("uploaded_at");

                    b.Property<Guid>("UploadedByMemberId")
                        .HasColumnType("uuid")
                        .HasColumnName("uploaded_by_member_id");

                    b.HasKey("Id")
                        .HasName("pk_attachments");

                    b.HasIndex("OwnerType", "OwnerEntityId")
                        .HasDatabaseName("ix_attachments_owner_type_owner_entity_id");

                    b.ToTable("attachments", (string)null);
                });

            modelBuilder.Entity("FamilyCare.Domain.MedicalHistory.ChronicCondition", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateOnly>("DiagnosedAt")
                        .HasColumnType("date")
                        .HasColumnName("diagnosed_at");

                    b.Property<Guid>("FamilyMemberId")
                        .HasColumnType("uuid")
                        .HasColumnName("family_member_id");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("name");

                    b.Property<string>("Notes")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("notes");

                    b.HasKey("Id")
                        .HasName("pk_chronic_conditions");

                    b.HasIndex("FamilyMemberId", "IsActive")
                        .HasDatabaseName("ix_chronic_conditions_family_member_id_is_active");

                    b.ToTable("chronic_conditions", (string)null);
                });

            modelBuilder.Entity("FamilyCare.Domain.MedicalHistory.Exam", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateOnly>("ExamDate")
                        .HasColumnType("date")
                        .HasColumnName("exam_date");

                    b.Property<string>("ExamType")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("exam_type");

                    b.Property<Guid>("FamilyMemberId")
                        .HasColumnType("uuid")
                        .HasColumnName("family_member_id");

                    b.Property<string>("Laboratory")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("laboratory");

                    b.Property<string>("RequestedBy")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("requested_by");

                    b.Property<string>("Results")
                        .HasMaxLength(8000)
                        .HasColumnType("character varying(8000)")
                        .HasColumnName("results");

                    b.HasKey("Id")
                        .HasName("pk_exams");

                    b.HasIndex("FamilyMemberId", "ExamDate")
                        .HasDatabaseName("ix_exams_family_member_id_exam_date");

                    b.ToTable("exams", (string)null);
                });

            modelBuilder.Entity("FamilyCare.Domain.MedicalHistory.Vaccine", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateOnly>("AppliedAt")
                        .HasColumnType("date")
                        .HasColumnName("applied_at");

                    b.Property<string>("BatchNumber")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("batch_number");

                    b.Property<int?>("DoseNumber")
                        .HasColumnType("integer")
                        .HasColumnName("dose_number");

                    b.Property<Guid>("FamilyMemberId")
                        .HasColumnType("uuid")
                        .HasColumnName("family_member_id");

                    b.Property<string>("Manufacturer")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("manufacturer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("name");

                    b.Property<DateOnly?>("NextDoseDue")
                        .HasColumnType("date")
                        .HasColumnName("next_dose_due");

                    b.Property<string>("Notes")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("notes");

                    b.HasKey("Id")
                        .HasName("pk_vaccines");

                    b.HasIndex("NextDoseDue")
                        .HasDatabaseName("ix_vaccines_next_dose_due");

                    b.HasIndex("FamilyMemberId", "AppliedAt")
                        .HasDatabaseName("ix_vaccines_family_member_id_applied_at");

                    b.ToTable("vaccines", (string)null);
                });

            modelBuilder.Entity("FamilyCare.Domain.FamilyManagement.FamilyMember", b =>
                {
                    b.HasOne("FamilyCare.Domain.FamilyManagement.Family", null)
                        .WithMany("Members")
                        .HasForeignKey("FamilyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_family_members_families_family_id");
                });

            modelBuilder.Entity("FamilyCare.Domain.FamilyManagement.Invitation", b =>
                {
                    b.HasOne("FamilyCare.Domain.FamilyManagement.Family", null)
                        .WithMany("Invitations")
                        .HasForeignKey("FamilyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_invitations_families_family_id");
                });

            modelBuilder.Entity("FamilyCare.Domain.FamilyManagement.PrivacyRule", b =>
                {
                    b.HasOne("FamilyCare.Domain.FamilyManagement.FamilyMember", null)
                        .WithMany("PrivacyRules")
                        .HasForeignKey("FamilyMemberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_privacy_rules_family_members_family_member_id");
                });

            modelBuilder.Entity("FamilyCare.Domain.FamilyManagement.Family", b =>
                {
                    b.Navigation("Invitations");

                    b.Navigation("Members");
                });

            modelBuilder.Entity("FamilyCare.Domain.FamilyManagement.FamilyMember", b =>
                {
                    b.Navigation("PrivacyRules");
                });
#pragma warning restore 612, 618
        }
    }
}
